# Generated by Django 3.0 on 2020-01-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_station'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('name', 'area')},
        ),
    ]
