# Generated by Django 3.0 on 2020-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200109_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('terminalStation1', models.CharField(max_length=100)),
                ('terminalStation2', models.CharField(max_length=100)),
                ('stations', models.ManyToManyField(to='website.Station')),
            ],
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('terminalStation1', models.CharField(max_length=100)),
                ('terminalStation2', models.CharField(max_length=100)),
                ('stations', models.ManyToManyField(to='website.Station')),
            ],
        ),
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('terminalStation1', models.CharField(max_length=100)),
                ('terminalStation2', models.CharField(max_length=100)),
                ('stations', models.ManyToManyField(to='website.Station')),
            ],
        ),
    ]
